# Generated by Django 3.2.25 on 2024-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=45)),
                ('reply', models.CharField(max_length=45)),
                ('date_time', models.DateField()),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
