# Generated by Django 3.2.25 on 2024-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=45)),
                ('p_price', models.CharField(max_length=45)),
                ('p_image', models.CharField(max_length=45)),
                ('p_type', models.CharField(max_length=45)),
                ('p_quantity', models.CharField(max_length=45)),
                ('p_color', models.CharField(max_length=10)),
                ('p_thickness', models.CharField(max_length=10)),
                ('p_pattern', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
