# Generated by Django 3.2.25 on 2025-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=45)),
                ('custom', models.CharField(max_length=45)),
                ('products', models.CharField(max_length=45)),
                ('amount', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('user', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
    ]
