# Generated by Django 3.2.25 on 2024-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('u_phone', models.CharField(max_length=45)),
                ('u_email', models.CharField(max_length=500)),
                ('u_proof', models.CharField(max_length=500)),
                ('u_place', models.CharField(max_length=20)),
                ('u_post', models.CharField(max_length=10)),
                ('u_district', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
