# Generated by Django 3.2.25 on 2024-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField()),
                ('quantity', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
